#!/usr/bin/env python3
"""Rebuild public docs from registered source repositories.

The source registry lives in docs-automation.json. This script is intentionally
config-driven: repo locations, inclusion policy, output prefixes, and nav tabs
come from the registry instead of absolute paths embedded in code.
"""

from __future__ import annotations

import fnmatch
import hashlib
import html
import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "docs-automation.json"
DOCS_JSON_PATH = ROOT / "docs.json"
MANIFEST_PATH = ROOT / "public-docs-manifest.json"
INVENTORY_PATH = ROOT / "public-docs-inventory.json"
LLMS_PATH = ROOT / "llms.txt"
LLMS_FULL_PATH = ROOT / "llms-full.txt"
DEFAULT_HEADER = "<!-- generated by scripts/rebuild-public-sources.py; do not edit manually -->"


@dataclass
class GeneratedPage:
    page_path: str
    title: str
    description: str
    source_id: str
    source_repo: str
    source_path: str
    source_sha256: str
    content_sha256: str


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def slugify(value: str) -> str:
    value = html.unescape(value).strip().lower()
    value = value.replace("&", " and ")
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return re.sub(r"-+", "-", value).strip("-") or "page"


def title_from_markdown(markdown: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+)$", markdown, re.MULTILINE)
    if match:
        return re.sub(r"\s+", " ", match.group(1)).strip()
    return fallback


def description_from_markdown(markdown: str, fallback: str) -> str:
    frontmatter = parse_frontmatter(markdown)
    if frontmatter.get("description"):
        return str(frontmatter["description"]).strip()
    body = strip_frontmatter(markdown)
    for raw_line in body.splitlines():
        line = re.sub(r"<[^>]+>", "", raw_line).strip()
        if not line or line.startswith("#") or line.startswith("|") or line.startswith("<!--"):
            continue
        line = re.sub(r"[*_`\\]", "", line)
        line = re.sub(r"\s+", " ", line)
        if len(line) >= 20:
            return line[:180]
    return fallback


def parse_frontmatter(markdown: str) -> dict[str, str]:
    if not markdown.startswith("---\n"):
        return {}
    end = markdown.find("\n---", 4)
    if end == -1:
        return {}
    result: dict[str, str] = {}
    for line in markdown[4:end].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = value.strip().strip('"').strip("'")
    return result


def strip_frontmatter(markdown: str) -> str:
    if not markdown.startswith("---\n"):
        return markdown
    end = markdown.find("\n---", 4)
    if end == -1:
        return markdown
    return markdown[end + 4 :].lstrip()


def escape_frontmatter(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def resolve_repo_root(source: dict[str, Any]) -> Path | None:
    env_name = source.get("rootEnv")
    candidates: list[Path] = []
    if env_name and os.environ.get(env_name):
        candidates.append(Path(os.environ[env_name]).expanduser())
    if source.get("localPath"):
        candidates.append((ROOT / source["localPath"]).resolve())
    repo_name = str(source.get("repo", "")).split("/")[-1]
    if repo_name:
        candidates.append((ROOT.parent / repo_name).resolve())
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def git_commit(repo_root: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return "unknown"


def path_matches(path: str, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


def iter_markdown_files(root: Path, source: dict[str, Any]) -> list[Path]:
    include_patterns = source.get("sourceGlobs") or ["**/*.md", "**/*.mdx"]
    exclude_patterns = source.get("exclude") or []
    files: dict[Path, None] = {}
    for pattern in include_patterns:
        for candidate in root.glob(pattern):
            if not candidate.is_file():
                continue
            rel = candidate.relative_to(root).as_posix()
            if path_matches(rel, exclude_patterns):
                continue
            files[candidate] = None
    return sorted(files)


def ensure_public_allowed(source: dict[str, Any], markdown: str) -> bool:
    if source.get("publicSafe") is True:
        return True
    frontmatter = parse_frontmatter(markdown)
    public_value = str(frontmatter.get("public", "")).lower()
    if public_value in {"true", "yes", "1"}:
        return True
    if re.search(r"<!--\s*lucid-public\s*:\s*true\s*-->", markdown, re.IGNORECASE):
        return True
    return False


def copy_asset_path(source_path: Path) -> str:
    if not source_path.exists() or not source_path.is_file():
        return source_path.as_posix()
    digest = hashlib.sha256(str(source_path).encode("utf-8")).hexdigest()[:10]
    extension = source_path.suffix.lower() or ".asset"
    name = f"{slugify(source_path.stem)}-{digest}{extension}"
    target = ROOT / "images" / "wiki" / name
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, target)
    return f"/images/wiki/{name}"


def copy_asset(repo_root: Path, source_dir: Path, asset_ref: str) -> str:
    candidate = (source_dir / asset_ref).resolve()
    if not candidate.exists():
        candidate = (repo_root / asset_ref).resolve()
    return copy_asset_path(candidate)


def github_blob_url(repo: str, rel_path: str) -> str:
    return f"https://github.com/{repo}/blob/main/{rel_path}"


def rewrite_links(markdown: str, repo_root: Path, output_prefix: str, source_dir: Path, source_cfg: dict[str, Any]) -> str:
    def replace_markdown_link(match: re.Match[str]) -> str:
        label = match.group(1)
        href = match.group(2).strip()
        if href in {"broken-reference"} or href.startswith("/broken/"):
            return label
        if href.startswith(("#", "http://", "https://", "mailto:", "/")):
            return match.group(0)
        if ".gitbook/assets/" in href:
            return f"![{label}]({copy_asset(repo_root, source_dir, href)})"
        href_path, hash_part = (href.split("#", 1) + [""])[:2] if "#" in href else (href, "")
        target = (source_dir / href_path).resolve()
        if href_path.endswith("/"):
            target = target / "README.md"
        if href_path.endswith(".md") or target.name == "README.md":
            try:
                rel = target.relative_to(repo_root).as_posix()
            except ValueError:
                return match.group(0)
            if source_cfg.get("linkMode") == "github":
                return f"[{label}]({github_blob_url(source_cfg['repo'], rel)})"
            public_path = page_path_for_source(output_prefix, rel)
            anchor = f"#{hash_part}" if hash_part else ""
            return f"[{label}](/{public_path}{anchor})"
        if source_cfg.get("linkMode") == "github" and target.exists():
            try:
                rel = target.relative_to(repo_root).as_posix()
            except ValueError:
                return match.group(0)
            return f"[{label}]({github_blob_url(source_cfg['repo'], rel)})"
        return match.group(0)

    markdown = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", replace_markdown_link, markdown)
    markdown = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", replace_markdown_link, markdown)

    def replace_html_src(match: re.Match[str]) -> str:
        quote = match.group(1)
        href = match.group(2)
        if ".gitbook/assets/" in href:
            return f"src={quote}{copy_asset(repo_root, source_dir, href)}{quote}"
        return match.group(0)

    markdown = re.sub(r"src=(['\"])([^'\"]+)\1", replace_html_src, markdown)
    markdown = re.sub(r"^\s*{%\s*hint[^%]*%}\s*$", "<Info>", markdown, flags=re.MULTILINE)
    markdown = re.sub(r"^\s*{%\s*endhint\s*%}\s*$", "</Info>", markdown, flags=re.MULTILINE)
    return markdown


def page_path_for_source(output_prefix: str, rel_source_path: str) -> str:
    without_ext = re.sub(r"\.(md|mdx)$", "", rel_source_path)
    if without_ext == "README":
        without_ext = "overview"
    without_ext = without_ext.replace("/README", "")
    parts = [slugify(part) for part in without_ext.split("/") if part]
    return "/".join([output_prefix.strip("/"), *parts])


def render_mdx(title: str, description: str, body: str, header: str, source: dict[str, str]) -> str:
    body = strip_frontmatter(body).strip()
    body = re.sub(r"^#\s+.+\n+", "", body, count=1).strip()
    source_comment = (
        f"<!-- source: {source['repo']}:{source['path']} "
        f"sha256:{source['sha256'][:12]} -->"
    )
    return "\n".join(
        [
            "---",
            f"title: {escape_frontmatter(title)}",
            f"description: {escape_frontmatter(description)}",
            "---",
            "",
            header,
            source_comment,
            "",
            f"# {title}",
            "",
            body,
            "",
        ]
    )


def write_page(
    page_path: str,
    title: str,
    description: str,
    body: str,
    source_cfg: dict[str, Any],
    source_rel_path: str,
    header: str,
) -> GeneratedPage:
    source_hash = sha256_text(body)
    mdx = render_mdx(
        title,
        description,
        body,
        header,
        {
            "repo": source_cfg["repo"],
            "path": source_rel_path,
            "sha256": source_hash,
        },
    )
    target = ROOT / f"{page_path}.mdx"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(mdx, encoding="utf-8")
    return GeneratedPage(
        page_path=page_path,
        title=title,
        description=description,
        source_id=source_cfg["id"],
        source_repo=source_cfg["repo"],
        source_path=source_rel_path,
        source_sha256=source_hash,
        content_sha256=sha256_text(mdx),
    )


def parse_summary(summary_text: str) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    current_group = "Guide"
    for raw_line in summary_text.splitlines():
        section = re.match(r"^##\s+(.+)$", raw_line)
        if section:
            current_group = section.group(1).strip()
            continue
        item = re.match(r"^(\s*)\*\s+\[([^\]]+)\]\(([^)]+)\)", raw_line)
        if not item:
            continue
        indent = len(item.group(1).replace("\t", "  "))
        entries.append(
            {
                "level": indent // 2,
                "group": current_group,
                "title": item.group(2).strip(),
                "source": item.group(3).strip(),
            }
        )
    return entries


def sync_gitbook_summary(source: dict[str, Any], repo_root: Path, header: str) -> tuple[list[GeneratedPage], dict[str, list[str]], list[dict[str, str]]]:
    summary_path = repo_root / source.get("summary", "SUMMARY.md")
    if not summary_path.exists():
        raise RuntimeError(f"Summary file not found: {summary_path}")
    entries = parse_summary(summary_path.read_text(encoding="utf-8"))
    exclude = source.get("exclude") or []
    output_prefix = source["outputPrefix"].strip("/")
    pages: list[GeneratedPage] = []
    nav_groups: dict[str, list[str]] = {}
    skipped: list[dict[str, str]] = []

    for entry in entries:
        source_rel = entry["source"]
        if path_matches(source_rel, exclude):
            skipped.append({"source": source_rel, "reason": "excluded"})
            continue
        src = (repo_root / source_rel).resolve()
        if not src.exists():
            skipped.append({"source": source_rel, "reason": "missing"})
            continue
        raw = src.read_text(encoding="utf-8")
        if not ensure_public_allowed(source, raw):
            skipped.append({"source": source_rel, "reason": "not public-marked"})
            continue
        page_path = page_path_for_source(output_prefix, source_rel)
        body = rewrite_links(raw, repo_root, output_prefix, src.parent, source)
        title = title_from_markdown(body, entry["title"])
        description = description_from_markdown(body, title)
        pages.append(write_page(page_path, title, description, body, source, source_rel, header))
        nav_groups.setdefault(entry["group"], []).append(page_path)

    return pages, nav_groups, skipped


def sync_markdown_tree(source: dict[str, Any], repo_root: Path, header: str) -> tuple[list[GeneratedPage], dict[str, list[str]], list[dict[str, str]]]:
    output_prefix = source["outputPrefix"].strip("/")
    pages: list[GeneratedPage] = []
    nav_groups: dict[str, list[str]] = {}
    skipped: list[dict[str, str]] = []

    for src in iter_markdown_files(repo_root, source):
        rel = src.relative_to(repo_root).as_posix()
        raw = src.read_text(encoding="utf-8")
        if not ensure_public_allowed(source, raw):
            skipped.append({"source": rel, "reason": "not public-marked"})
            continue
        path_tail = re.sub(r"^docs/", "", rel)
        page_path = page_path_for_source(output_prefix, path_tail)
        body = rewrite_links(raw, repo_root, output_prefix, src.parent, source)
        title = title_from_markdown(body, Path(rel).stem.replace("-", " ").title())
        description = description_from_markdown(body, title)
        pages.append(write_page(page_path, title, description, body, source, rel, header))
        parts = path_tail.split("/")
        group = parts[0].replace("-", " ").title() if len(parts) > 1 else "Reference"
        nav_groups.setdefault(group, []).append(page_path)

    return pages, nav_groups, skipped


def extract_operations(markdown: str) -> list[tuple[str, str]]:
    operations: list[tuple[str, str]] = []
    for line in markdown.splitlines():
        match = re.match(r"\*\s+\[([^\]]+)\]\([^)]+\)\s+-\s+(.+)", line.strip())
        if match:
            operations.append((match.group(1).strip(), match.group(2).strip()))
    return operations


def sync_sdk_namespace_tree(source: dict[str, Any], repo_root: Path, header: str) -> tuple[list[GeneratedPage], dict[str, list[str]], list[dict[str, str]]]:
    source_root = repo_root / source["sourceRoot"]
    pages: list[GeneratedPage] = []
    skipped: list[dict[str, str]] = []
    nav_groups: dict[str, list[str]] = {"Namespaces": []}
    if not source_root.exists():
        return pages, nav_groups, [{"source": source["sourceRoot"], "reason": "missing"}]

    rows = ["| Namespace | Operations |", "| --- | ---: |"]
    for readme in sorted(source_root.glob("*/README.md")):
        namespace = readme.parent.name
        rel = readme.relative_to(repo_root).as_posix()
        raw = readme.read_text(encoding="utf-8")
        if not ensure_public_allowed(source, raw):
            skipped.append({"source": rel, "reason": "not public-marked"})
            continue
        page_path = f"{source['outputPrefix'].strip('/')}/namespaces/{slugify(namespace)}"
        body = rewrite_links(raw, repo_root, source["outputPrefix"].strip("/"), readme.parent, source)
        title = f"{namespace.replace('-', ' ').title()} SDK"
        description = description_from_markdown(body, f"{title} namespace reference.")
        pages.append(write_page(page_path, title, description, body, source, rel, header))
        nav_groups["Namespaces"].append(page_path)
        rows.append(f"| [`{namespace}`](/{page_path}) | {len(extract_operations(raw))} |")

    index_body = "\n".join(
        [
            "Gateway SDK namespace pages are generated from the current gateway SDK docs.",
            "",
            *rows,
        ]
    )
    index_page = f"{source['outputPrefix'].strip('/')}/index"
    pages.insert(
        0,
        write_page(
            index_page,
            "Gateway SDK Reference",
            "Generated gateway SDK namespace index.",
            index_body,
            source,
            source["sourceRoot"],
            header,
        ),
    )
    nav_groups = {"Overview": [index_page], "Namespaces": nav_groups["Namespaces"]}
    return pages, nav_groups, skipped


def inventory_only(source: dict[str, Any], repo_root: Path) -> tuple[list[GeneratedPage], dict[str, list[str]], list[dict[str, str]]]:
    skipped: list[dict[str, str]] = []
    for src in iter_markdown_files(repo_root, source):
        rel = src.relative_to(repo_root).as_posix()
        raw = src.read_text(encoding="utf-8", errors="replace")
        reason = "public-marked but inventory-only" if ensure_public_allowed(source, raw) else "private-default"
        skipped.append({"source": rel, "reason": reason})
    return [], {}, skipped


def upsert_generated_tab(docs_json: dict[str, Any], tab_name: str, groups: dict[str, list[str]], order: int) -> None:
    tabs = docs_json.setdefault("navigation", {}).setdefault("tabs", [])
    tabs[:] = [tab for tab in tabs if tab.get("tab") != tab_name]
    if not groups:
        return
    rendered_groups = [
        {"group": group_name, "pages": sorted(dict.fromkeys(pages))}
        for group_name, pages in groups.items()
        if pages
    ]
    if not rendered_groups:
        return
    tab = {"tab": tab_name, "groups": rendered_groups}
    tabs.append(tab)


def update_navigation(nav_by_tab: dict[str, dict[str, Any]], tab_order: list[str]) -> None:
    docs_json = load_json(DOCS_JSON_PATH)
    for tab_name, tab_info in nav_by_tab.items():
        upsert_generated_tab(docs_json, tab_name, tab_info["groups"], tab_info["order"])
    if tab_order:
        order = {name: index for index, name in enumerate(tab_order)}
        tabs = docs_json.setdefault("navigation", {}).setdefault("tabs", [])
        tabs.sort(key=lambda tab: (order.get(tab.get("tab"), len(order)), tab.get("tab", "")))
    DOCS_JSON_PATH.write_text(json.dumps(docs_json, indent=2) + "\n", encoding="utf-8")


def render_llms(manifest: dict[str, Any], full: bool) -> str:
    lines = [
        "# Lucid Documentation",
        "",
        "> Public documentation for Lucid, generated from source-controlled docs, OpenAPI, and SDK references.",
        "",
    ]
    by_source: dict[str, list[dict[str, Any]]] = {}
    for page in manifest["pages"]:
        by_source.setdefault(page["source_id"], []).append(page)
    for source_id, pages in sorted(by_source.items()):
        lines.append(f"## {source_id}")
        lines.append("")
        for page in sorted(pages, key=lambda item: item["page_path"]):
            lines.append(f"- [{page['title']}](/{page['page_path']}): {page['description']}")
            if full:
                mdx_path = ROOT / f"{page['page_path']}.mdx"
                if mdx_path.exists():
                    body = strip_frontmatter(mdx_path.read_text(encoding="utf-8"))
                    lines.append("")
                    lines.extend(line.rstrip() for line in body.strip()[:12000].splitlines())
                    lines.append("")
        lines.append("")
    return "\n".join(line.rstrip() for line in lines).rstrip() + "\n"


def main() -> None:
    config = load_json(CONFIG_PATH)
    header = config.get("generatedHeader", DEFAULT_HEADER)
    manifest_pages: list[GeneratedPage] = []
    inventory: dict[str, Any] = {"sources": []}
    nav_by_tab: dict[str, dict[str, Any]] = {}

    for source in config["sources"]:
        repo_root = resolve_repo_root(source)
        source_record: dict[str, Any] = {
            "id": source["id"],
            "repo": source["repo"],
            "adapter": source["adapter"],
            "visibility": source.get("visibility", "unknown"),
            "publicSafe": bool(source.get("publicSafe")),
            "root": str(repo_root) if repo_root else None,
            "commit": git_commit(repo_root) if repo_root else None,
            "generatedPages": [],
            "skipped": [],
        }
        if repo_root is None:
            source_record["skipped"].append({"source": source["repo"], "reason": "repo root unavailable"})
            inventory["sources"].append(source_record)
            print(f"skipped {source['id']}: repo root unavailable")
            continue

        adapter = source["adapter"]
        if adapter == "gitbook-summary":
            pages, groups, skipped = sync_gitbook_summary(source, repo_root, header)
        elif adapter == "markdown-tree":
            pages, groups, skipped = sync_markdown_tree(source, repo_root, header)
        elif adapter == "sdk-namespace-tree":
            pages, groups, skipped = sync_sdk_namespace_tree(source, repo_root, header)
        elif adapter == "inventory-only":
            pages, groups, skipped = inventory_only(source, repo_root)
        else:
            raise RuntimeError(f"Unknown adapter: {adapter}")

        source_record["generatedPages"] = [page.page_path for page in pages]
        source_record["skipped"] = skipped
        inventory["sources"].append(source_record)
        manifest_pages.extend(pages)

        tab_name = source.get("navigationTab")
        if tab_name and groups:
            tab_info = nav_by_tab.setdefault(
                tab_name,
                {"order": int(source.get("navigationOrder", 100)), "groups": {}},
            )
            tab_info["order"] = min(tab_info["order"], int(source.get("navigationOrder", 100)))
            for group_name, page_paths in groups.items():
                tab_info["groups"].setdefault(group_name, []).extend(page_paths)

        print(f"{source['id']}: generated {len(pages)} page(s), skipped {len(skipped)}")

    update_navigation(nav_by_tab, config.get("tabOrder", []))
    manifest = {
        "version": config["version"],
        "generatedBy": "scripts/rebuild-public-sources.py",
        "pageCount": len(manifest_pages),
        "sources": [
            {
                "id": src["id"],
                "repo": src["repo"],
                "adapter": src["adapter"],
                "commit": src.get("commit"),
                "generatedPageCount": len(src["generatedPages"]),
                "skippedCount": len(src["skipped"]),
            }
            for src in inventory["sources"]
        ],
        "pages": [page.__dict__ for page in sorted(manifest_pages, key=lambda item: item.page_path)],
    }
    write_json(MANIFEST_PATH, manifest)
    write_json(INVENTORY_PATH, inventory)
    LLMS_PATH.write_text(render_llms(manifest, full=False), encoding="utf-8")
    LLMS_FULL_PATH.write_text(render_llms(manifest, full=True), encoding="utf-8")
    print(f"generated manifest with {len(manifest_pages)} page(s)")


if __name__ == "__main__":
    main()
