#!/usr/bin/env python3
"""Lightweight docs validation for the Mintlify repo."""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DOCS_JSON = ROOT / "docs.json"
MANIFEST = ROOT / "public-docs-manifest.json"


def iter_pages(node: Any):
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "pages" and isinstance(value, list):
                for page in value:
                    if isinstance(page, str) and not page.startswith(("GET ", "POST ", "PATCH ", "PUT ", "DELETE ")):
                        yield page
            else:
                yield from iter_pages(value)
    elif isinstance(node, list):
        for item in node:
            yield from iter_pages(item)


def validate_page_exists(page: str) -> str | None:
    path = ROOT / f"{page}.mdx"
    if not path.exists():
        return f"Missing docs.json page target: {page}.mdx"
    if not path.read_text(encoding="utf-8").strip():
        return f"Empty docs page: {page}.mdx"
    return None


def validate_openapi_urls(node: Any) -> list[str]:
    errors: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "openapi" and isinstance(value, str) and value.startswith("https://"):
                try:
                    with urllib.request.urlopen(
                        urllib.request.Request(value, headers={"User-Agent": "lucid-docs-validate"}),
                        timeout=20,
                    ) as response:
                        if response.status >= 400:
                            errors.append(f"OpenAPI URL returned HTTP {response.status}: {value}")
                except Exception as exc:
                    errors.append(f"OpenAPI URL is not reachable: {value} ({exc})")
            else:
                errors.extend(validate_openapi_urls(value))
    elif isinstance(node, list):
        for item in node:
            errors.extend(validate_openapi_urls(item))
    return errors


def validate_manifest() -> list[str]:
    if not MANIFEST.exists():
        return ["Missing public docs manifest: public-docs-manifest.json"]
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    errors: list[str] = []
    pages = manifest.get("pages")
    if not isinstance(pages, list) or not pages:
        return ["public-docs-manifest.json has no generated pages"]
    for page in pages:
        page_path = page.get("page_path")
        if not isinstance(page_path, str):
            errors.append("Manifest page missing page_path")
            continue
        mdx_path = ROOT / f"{page_path}.mdx"
        if not mdx_path.exists():
            errors.append(f"Manifest target does not exist: {page_path}.mdx")
            continue
        content = mdx_path.read_text(encoding="utf-8")
        if "generated by scripts/rebuild-public-sources.py" not in content:
            errors.append(f"Generated page missing source header: {page_path}.mdx")
    return errors


def validate_local_links() -> list[str]:
    errors: list[str] = []
    link_pattern = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
    image_pattern = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")
    href_pattern = re.compile(r"href=[\"']([^\"']+)[\"']")
    for path in sorted(ROOT.rglob("*.mdx")):
        rel_path = path.relative_to(ROOT).as_posix()
        content = path.read_text(encoding="utf-8")
        for pattern in (link_pattern, image_pattern, href_pattern):
            for match in pattern.finditer(content):
                href = match.group(1).strip()
                if not href or href.startswith(("#", "http://", "https://", "mailto:")):
                    continue
                href = href.split("#", 1)[0]
                if href.startswith("/"):
                    candidate = ROOT / href.lstrip("/")
                else:
                    candidate = path.parent / href
                if candidate.suffix == "":
                    if (candidate.with_suffix(".mdx")).exists() or candidate.exists():
                        continue
                    errors.append(f"Broken local link in {rel_path}: {match.group(1)}")
                elif not candidate.exists():
                    errors.append(f"Broken local link in {rel_path}: {match.group(1)}")
    return errors


def main() -> int:
    docs = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    errors = []
    for page in sorted(set(iter_pages(docs))):
        error = validate_page_exists(page)
        if error:
            errors.append(error)
    errors.extend(validate_openapi_urls(docs))
    errors.extend(validate_manifest())
    errors.extend(validate_local_links())

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    print("Docs validation passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
